### ISSUE TITLE
Linux build broken after commit a71d2aae38139d7d3e981d93b8ef1daabfed3cd7

### ISSUE THREAD

**Issue by DennZo1993** [DennZo1993/OPAL#10]
Compilation error (Clang, GCC the same):

```
[  6%] Building CXX object lib/CMakeFiles/libOPAL.dir/OPAL.cpp.o
In file included from /home/travis/build/DennZo1993/OPAL/lib/OPAL.cpp:1:
In file included from /home/travis/build/DennZo1993/OPAL/lib/OPAL.h:3:
/home/travis/build/DennZo1993/OPAL/lib/Matrix.h:446:14: error: comparison of
      integers of different signs: 'unsigned int' and 'int'
      [-Werror,-Wsign-compare]
    if (!(i1 >= patchRadY && i2 >= patchRadY &&
```

**Comment by DennZo1993** [comment]
Bad commit: a71d2aae38139d7d3e981d93b8ef1daabfed3cd7

**Comment by DennZo1993** [comment]
Fixed in ae776f6589b44605a6e6c062121482de1bbf3f93
